import user1 from "@/assets/images/users/user-1.jpg";
import user2 from "@/assets/images/users/user-2.jpg";
import user3 from "@/assets/images/users/user-3.jpg";
import user4 from "@/assets/images/users/user-4.jpg";
import user5 from "@/assets/images/users/user-5.jpg";
import user6 from "@/assets/images/users/user-6.jpg";

export const homeTable = [
    {
      company: user1,
      category: "Ornamental Railings",
      views: 343,
      revenue: "$231.26",
      sales: 95,
      up: false,
    },
    {
      company: user2,
      category: "Asphalt Paving",
      views: 315,
      revenue: "$432.81",
      sales: 197,
      up: false,
    },
    {
      company: user3,
      category: "Framing (Steel)",
      views: 329,
      revenue: "$437.65",
      sales: 137,
      up: true,
    },
    {
      company: user4,
      category: "Structural and Misc Steel (Fabrication)",
      views: 336,
      revenue: "$387.55",
      sales: 101,
      up: true,
    },
    {
      company: user5,
      category: "Wall Protection",
      views: 375,
      revenue: "$489.80",
      sales: 99,
      up: false,
    },
    {
      company: user6,
      category: "Marlite Panels (FED)",
      views: 490,
      revenue: "$421.45",
      sales: 101,
      up: true,
    },
    {
      company: user1,
      category: "Epoxy Flooring",
      views: 433,
      revenue: "$207.61",
      sales: 197,
      up: false,
    },
    {
      company: user2,
      category: "Epoxy Flooring",
      views: 499,
      revenue: "$392.86",
      sales: 91,
      up: false,
    },
    {
      company: user3,
      category: "Marlite Panels (FED)",
      views: 441,
      revenue: "$162.87",
      sales: 115,
      up: false,
    },
    {
      company: user4,
      category: "RF Shielding",
      views: 415,
      revenue: "$268.58",
      sales: 128,
      up: false,
    },
    {
      company: user5,
      category: "Roofing (Metal)",
      views: 303,
      revenue: "$369.19",
      sales: 179,
      up: false,
    },
    {
      company: user6,
      category: "RF Shielding",
      views: 415,
      revenue: "$420.87",
      sales: 148,
      up: false,
    },
    {
      company: user1,
      category: "Curb & Gutter",
      views: 493,
      revenue: "$420.26",
      sales: 152,
      up: false,
    },
    {
      company: user2,
      category: "Structural & Misc Steel Erection",
      views: 498,
      revenue: "$228.41",
      sales: 151,
      up: false,
    },
    {
      company: user3,
      category: "Retaining Wall and Brick Pavers",
      views: 465,
      revenue: "$140.83",
      sales: 71,
      up: false,
    },
    {
      company: user4,
      category: "Sitework & Site Utilities",
      views: 468,
      revenue: "$475.63",
      sales: 114,
      up: false,
    },
    {
      company: user5,
      category: "Framing (Steel)",
      views: 357,
      revenue: "$415.37",
      sales: 163,
      up: false,
    },
    {
      company: user6,
      category: "Waterproofing & Caulking",
      views: 487,
      revenue: "$436.53",
      sales: 170,
      up: false,
    },
    {
      company: user1,
      category: "Site Furnishings",
      views: 357,
      revenue: "$147.36",
      sales: 71,
      up: false,
    },
    {
      company: user2,
      category: "Casework",
      views: 465,
      revenue: "$121.67",
      sales: 78,
      up: false,
    },
    {
      company: user3,
      category: "Ornamental Railings",
      views: 438,
      revenue: "$213.25",
      sales: 155,
      up: false,
    },
    {
      company: user4,
      category: "Waterproofing & Caulking",
      views: 461,
      revenue: "$186.48",
      sales: 137,
      up: false,
    },
    {
      company: user5,
      category: "Masonry",
      views: 423,
      revenue: "$130.97",
      sales: 178,
      up: false,
    },
    {
      company: user6,
      category: "Curb & Gutter",
      views: 339,
      revenue: "$255.69",
      sales: 101,
      up: false,
    },
    {
      company: user1,
      category: "HVAC",
      views: 361,
      revenue: "$484.64",
      sales: 175,
      up: true,
    },
    {
      company: user2,
      category: "Exterior Signage",
      views: 353,
      revenue: "$485.51",
      sales: 176,
      up: true,
    },
    {
      company: user3,
      category: "Fire Protection",
      views: 364,
      revenue: "$449.45",
      sales: 136,
      up: true,
    },
    {
      company: user4,
      category: "Rebar & Wire Mesh Install",
      views: 493,
      revenue: "$309.61",
      sales: 163,
      up: true,
    },
    {
      company: user5,
      category: "Temp Fencing, Decorative Fencing and Gates",
      views: 393,
      revenue: "$372.45",
      sales: 180,
      up: true,
    },
    {
      company: user6,
      category: "Fire Protection",
      views: 441,
      revenue: "$470.34",
      sales: 104,
      up: false,
    },
  ];
  